auto_gain: 'Off'
auto_white_balance: Continuous
enable_trigger: 'On'
exposure_auto: 'Off'
exposure_mode: Timed
exposure_time: 8000
gain: 5
gain_selector: All
image_format_color_coding: BayerRG8
trigger_overlap_mode: ReadOut
trigger_selector: FrameStart
trigger_source: Line3
