#STEREO CH3 SLAVE CONFIG DEEP SEA

# # ACQUISITION CONTROL
trigger_source: Line3
trigger_overlap_mode: ReadOut
trigger_selector: FrameStart
enable_trigger: "On"

# # IMAGE FORMAT CONTROL
image_format_color_coding: BayerRG8

# EXPOSURE
exposure_mode: Timed
exposure_auto: 'Off' 
#auto_exposure_time_upper_limit: 40000.0 # microseconds
exposure_time: 20000.0 # microseconds

# GAIN
gain_selector: All
auto_gain: 'Off' 
gain: 10.0

# WHITE BALANCE
auto_white_balance: "Continuous"
# white_balance_blue_ratio: 0
# white_balance_red_ratio: 1023


