#STEREO CH3 SLAVE

# # ACQUISITION CONTROL
trigger_source: Line3
trigger_overlap_mode: ReadOut
trigger_selector: FrameStart
enable_trigger: "On"

# # IMAGE FORMAT CONTROL
image_format_color_coding: BayerRG8

# EXPOSURE
exposure_mode: Timed
exposure_auto: 'Off'
#auto_exposure_time_upper_limit: 10000.0 # microseconds
exposure_time: 5000.0 #4500.0 # microseconds

# GAIN
gain_selector: All
auto_gain: 'Off'
gain: 0.0
