# FRAME RATE
acquisition_frame_rate_enable: True
acquisition_frame_rate: 4.0

# DIGITAL I/O FOR TRIGGER
line_selector: Line2
line_mode: Output
line_source: ExposureActive

# IMAGE FORMAT CONTROL
image_format_color_coding: BayerRG8

# EXPOSURE
exposure_mode: Timed
# exposure_auto: 'Off'
exposure_auto: Continuous
auto_exposure_time_upper_limit: 5500 # microseconds
# exposure_time: 5000 # microseconds

# GAIN
gain_selector: All
auto_gain: Continuous
gain: 0.0
