acquisition_frame_rate: 4.0
acquisition_frame_rate_enable: true
auto_gain: 'Off'
exposure_auto: 'Off'
exposure_mode: Timed
exposure_time: 50000
gain: 5.0
gain_selector: All
image_format_color_coding: BayerRG8
line_mode: Output
line_selector: Line2
line_source: ExposureActive
