#STEREO CH3 MASTER 

# FRAME RATE
acquisition_frame_rate_enable: True
acquisition_frame_rate: 4.0

# DIGITAL I/O FOR TRIGGER
line_selector: Line2
line_mode: Output
line_source: ExposureActive

# IMAGE FORMAT CONTROL
image_format_color_coding: BayerRG8

# EXPOSURE
exposure_mode: Timed
exposure_auto: 'Off' 
#auto_exposure_time_upper_limit: 40000.0 # microseconds
exposure_time: 20000.0 # microseconds

# GAIN
gain_selector: All
auto_gain: 'Off' 
gain: 10.0

# WHITE BALANCE
auto_white_balance: "Continuous"
# white_balance_blue_ratio: 0
# white_balance_red_ratio: 1023






